environment:
  matrix:
  - APPVEYOR_BUILD_SYS: Msys2
    WIN_SHELL: C:\msys32\usr\bin\bash
    WIN_MAKE:  C:\msys32\usr\bin\make
    WIN_SETUP: C:\msys32\usr\bin\bash
    SHELL: /usr/bin/bash
    MAKE:  /usr/bin/make
    SETUP: /usr/bin/bash
    CC:  /c/msys32/mingw32/bin/gcc
    CXX: /c/msys32/mingw32/bin/g++
    FC:  /c/msys32/mingw32/bin/gfortran
  - APPVEYOR_BUILD_SYS: Cygwin
    WIN_SHELL: C:\cygwin\bin\bash
    WIN_MAKE:  C:\cygwin\bin\make
    WIN_SETUP: C:\cygwin\setup-x86.exe
    SHELL: /cygdrive/c/cygwin/bin/bash
    MAKE:  /cygdrive/c/cygwin/bin/make
    SETUP: /cygdrive/c/cygwin/bin/setup-x86.exe
    CC:  /cygdrive/c/cygwin/bin/gcc
    CXX: /cygdrive/c/cygwin/bin/g++
    FC:  /cygdrive/c/cygwin/bin/gfortran

init:
  # Carriage returns are bad
  - cmd:
      'git config --global core.autocrlf input'

build: off

install:
  # coreutils (uname), findutils (find), util-linux (getopt)
  # bc (calculator), gcc-fortran (gforgran)
  - cmd:
      'if "%APPVEYOR_BUILD_SYS%" == "Msys2" (
        cd C:/
        & appveyor DownloadFile "http://kent.dl.sourceforge.net/project/msys2/Base/i686/msys2-base-i686-20150512.tar.xz" -FileName "msys2.tar.xz"
        & 7z x msys2.tar.xz
        & 7z x msys2.tar > NUL
        & %WIN_SETUP% -lc "pacman --noconfirm -Syu"
        & %WIN_SETUP% -lc "pacman --noconfirm -S bc"
        & %WIN_SETUP% -lc "pacman --noconfirm -S make"
        & %WIN_SETUP% -lc "pacman --noconfirm -S mingw-w64-i686-gcc"
        & %WIN_SETUP% -lc "pacman --noconfirm -S mingw-w64-i686-gcc-fortran"
        & cd %APPVEYOR_BUILD_FOLDER%
      )'
  - cmd:
      'if "%APPVEYOR_BUILD_SYS%" == "Cygwin"
         %WIN_SETUP% -q -P coreutils,findutils,util-linux,bc,gcc-core,gcc-g++,gcc-fortran'

before_test:
  - cmd:
      'if "%APPVEYOR_BUILD_SYS%" == "Msys2"
         set PATH=C:\msys32\usr\bin;C:\msys32\mingw32\bin;%PATH%'
  - cmd:
      'if "%APPVEYOR_BUILD_SYS%" == "Cygwin"
         set PATH=C:\cygwin\bin;%PATH%'

test_script:
  - cmd:
      '%WIN_SHELL% test/tests.sh'

